language: elixir

matrix:
  include:
    - otp_release: 21.0
      elixir: 1.6
    - otp_release: 21.3
      elixir: 1.7.4
    - otp_release: 21.3
      elixir: 1.8.1
    - otp_release: 22.0
      elixir: 1.8.1

env:
  global:
    - MIX_ENV=test

sudo: true

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y

install:
  - source $HOME/.cargo/env


script:
  - mix test
  - mix coveralls.travis